spring.mail.host=${GMAIL_HOST}
spring.mail.port=${GMAIL_PORT}
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_APP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

app.frontend.url=${FRONTEND_URL}
app.backend.url=${BACKEND_URL}