
server.port=${PORT:8080}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT
jwt.secret=${JWT_SECRET}

# Razorpay
razorpay.key-id=${RAZORPAY_KEY_ID}
razorpay.key-secret=${RAZORPAY_KEY_SECRET}
razorpay.webhook-secret=${RAZORPAY_WEBHOOK_SECRET}

# Fees
processing.fee.percent=2
platform.withdrawal.fee-percent=2

# Admin bootstrap
app.admin.bootstrap.enabled=${ADMIN_BOOTSTRAP:false}
app.admin.bootstrap.email=${ADMIN_EMAIL}
app.admin.bootstrap.password=${ADMIN_PASSWORD}

# URLs
app.payment.url=${PAYMENT_URL}
app.frontend.url=${FRONTEND_URL}
app.backend.url=${BACKEND_URL}



# MAIL
spring.mail.host=${GMAIL_HOST}
spring.mail.port=${GMAIL_PORT}
spring.mail.username=${GMAIL_USERNAME}
spring.mail.password=${GMAIL_APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
